ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.health_profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.photos ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.likes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.matches ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.messages ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.community_posts ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.community_replies ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.blocks ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.hides ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_filters ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view active profiles" ON public.users FOR SELECT USING (is_active = true);
CREATE POLICY "Users can update own profile" ON public.users FOR UPDATE USING (auth.uid() = id);
CREATE POLICY "Users can view own health profile" ON public.health_profiles FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Users can manage own health profile" ON public.health_profiles FOR ALL USING (auth.uid() = user_id);
CREATE POLICY "Photos are viewable by all" ON public.photos FOR SELECT USING (true);
CREATE POLICY "Users can manage own photos" ON public.photos FOR ALL USING (auth.uid() = user_id);
CREATE POLICY "Users can manage own likes" ON public.likes FOR ALL USING (auth.uid() = liker_id);
CREATE POLICY "Users can view own matches" ON public.matches FOR SELECT USING (auth.uid() = user1_id OR auth.uid() = user2_id);
CREATE POLICY "Users can view messages in their matches" ON public.messages FOR SELECT USING (EXISTS (SELECT 1 FROM public.matches WHERE id = match_id AND (user1_id = auth.uid() OR user2_id = auth.uid())));
CREATE POLICY "Users can send messages in their matches" ON public.messages FOR INSERT WITH CHECK (auth.uid() = sender_id AND EXISTS (SELECT 1 FROM public.matches WHERE id = match_id AND (user1_id = auth.uid() OR user2_id = auth.uid())));
CREATE POLICY "Community posts are viewable by all" ON public.community_posts FOR SELECT USING (true);
CREATE POLICY "Users can manage own posts" ON public.community_posts FOR ALL USING (auth.uid() = user_id);
CREATE POLICY "Community replies are viewable by all" ON public.community_replies FOR SELECT USING (true);
CREATE POLICY "Users can manage own replies" ON public.community_replies FOR ALL USING (auth.uid() = user_id);
CREATE POLICY "Users can manage own blocks" ON public.blocks FOR ALL USING (auth.uid() = blocker_id);
CREATE POLICY "Users can manage own hides" ON public.hides FOR ALL USING (auth.uid() = hider_id);
CREATE POLICY "Users can manage own filters" ON public.user_filters FOR ALL USING (auth.uid() = user_id);